(() => {
  'use strict';

  const N = 4;
  const FREQ_RANGES = [[20, 300, 0.1],[60, 1200, 0.1],[200, 3000, 0.1],[1000, 25000, 0.1]];
  const DEFAULT_FREQ = [31.5, 125, 1000, 8000];
  const DEFAULTS = DEFAULT_FREQ.map(freq => ({ freq, gain: 0, q: 1, denoise: 0, punch: 0, sustain: 0, bypass: false, solo: false }));
  const COMMON_LIMITS = { gain: [-24, 24, 0.1], q: [0.1, 20, 0.01], denoise: [0, 100, 1], punch: [-100, 100, 1], sustain: [-100, 100, 1] };
  const $ = id => document.getElementById(id);
  const clamp = (x, a, b) => Math.max(a, Math.min(b, x));
  const clone = a => a.map(x => ({ ...x }));
  let ctx = null, buffer = null, source = null, graph = null;
  let playing = false, offset = 0, startedAt = 0, raf = 0;
  let loop = false, loopStart = 0, loopEnd = 0, delta = 0, allBypass = false;
  let ab = 'A', slotA = clone(DEFAULTS), slotB = clone(DEFAULTS);
  let drag = null, renderTimer = 0, graphMode = '';
  function freqLimit(i){return FREQ_RANGES[i-1]||FREQ_RANGES[0]}
  function limitFor(key,i){return key==='freq'?freqLimit(i):COMMON_LIMITS[key]}
  function status(s){if($('status'))$('status').textContent=s}
  function data(){return Array.from({length:N},(_,i)=>{const k=i+1;return{freq:+$('freq'+k).value,gain:+$('gain'+k).value,q:+$('q'+k).value,denoise:+$('denoise'+k).value,punch:+$('punch'+k).value,sustain:+$('sustain'+k).value,bypass:!$('byp'+k).classList.contains('on'),solo:$('solo'+k).classList.contains('active')}})}
  function saveSlot(){if(ab==='A')slotA=data();else slotB=data()}
  function fmt(key,v){if(key==='freq')return v>=1000?(v/1000).toFixed(v>=10000?1:2)+' kHz':(v%1?v.toFixed(1):v.toFixed(0))+' Hz';if(key==='gain')return v.toFixed(1)+' dB';if(key==='q')return v.toFixed(2);return Math.round(v)+'%'}
  function drawKnob(input,show=false){const key=input.id.replace(/\d+$/,''),i=+(input.id.match(/\d+$/)?.[0]||1),[min,max]=limitFor(key,i),v=+input.value,knob=document.querySelector(`.knob[data-target="${input.id}"]`);if(!knob)return;const p=knob.querySelector('.knob-pointer');if(p)p.style.transform=`translateX(-50%) rotate(${-135+270*(v-min)/(max-min)}deg)`;const r=$(input.id+'Out');if(r){r.textContent=fmt(key,v);r.classList.toggle('show',show)}}
  function normalizeValue(key,i,value){const[min,max,step]=limitFor(key,i),d=(String(step).split('.')[1]||'').length;return Number((Math.round(clamp(Number(value),min,max)/step)*step).toFixed(d))}
  function setKnob(input,value,show=true){const key=input.id.replace(/\d+$/,''),i=+(input.id.match(/\d+$/)?.[0]||1);input.value=String(normalizeValue(key,i,value));drawKnob(input,show);input.dispatchEvent(new Event('input',{bubbles:true}))}
  function setBypass(i,on,update=true){const b=$('byp'+i);if(!b)return;b.classList.toggle('on',on);b.classList.toggle('off',!on);const st=document.querySelector(`.band[data-band="${i}"] .state`);if(st)st.textContent=on?'ON':'BYP';if(update){saveSlot();sync();renderProcessedSoon()}}
  function setSolo(i,active,update=true){const b=$('solo'+i);if(!b)return;b.classList.toggle('active',active);b.textContent=active?'SOLO ON':'SOLO';if(update){saveSlot();sync();renderProcessedSoon();const solos=data().map((x,n)=>x.solo?n+1:0).filter(Boolean);status(solos.length?`SOLO：SECTION ${solos.join('、')}`:'SOLO 已關閉')}}
  function apply(a,save=false){for(let i=1;i<=N;i++){const b=a[i-1]||DEFAULTS[i-1];for(const key of ['freq','gain','q','denoise','punch','sustain']){const input=$(key+i);if(!input)continue;input.value=String(normalizeValue(key,i,b[key]));drawKnob(input,false)}setBypass(i,!b.bypass,false);setSolo(i,!!b.solo,false)}if(save)saveSlot();sync();renderProcessedSoon()}
  function resetAll(){delta=0;allBypass=false;$('bypassAll').classList.remove('active');$('bypassAll').textContent='BYPASS OFF';apply(clone(DEFAULTS),true);updateDelta();status('所有 Sections 已重設。')}
  function resetBands(){apply(clone(DEFAULTS),true);delta=0;updateDelta();status('所有 Sections 已重設。')}
  function resetBand(i){const a=data();a[i-1]={...DEFAULTS[i-1]};apply(a,true);status('SECTION '+i+' 已重設。')}
  function sortBands(){apply(data().sort((a,b)=>a.freq-b.freq),true);status('Sections 已依頻率排序。')}
  function ensureCtx(){if(!ctx||ctx.state==='closed')ctx=new AudioContext();return ctx}
  function makeStage(){const c=ensureCtx(),band=c.createBiquadFilter(),eq=c.createBiquadFilter(),dry=c.createGain(),neg=c.createGain(),change=c.createGain(),normal=c.createGain(),deltaGate=c.createGain(),proc=c.createScriptProcessor(512,2,2);band.type='bandpass';eq.type='peaking';neg.gain.value=-1;const state={dFast:0,dSlow:0,dNoise:1e-5,dGain:1,dOpen:true,tFast:0,tSlow:0,settings:DEFAULTS[0]};proc.onaudioprocess=e=>{const inp=e.inputBuffer,out=e.outputBuffer,s=state,b=s.settings||DEFAULTS[0],frames=out.length,ch=Math.min(inp.numberOfChannels,out.numberOfChannels),amount=clamp(+b.denoise||0,0,100)/100,punch=(+b.punch||0)/100,sustain=(+b.sustain||0)/100;for(let i=0;i<frames;i++){let peak=0;for(let c=0;c<ch;c++)peak=Math.max(peak,Math.abs(inp.getChannelData(c)[i]));let dg=1;if(amount>0.0001){s.dFast+=(peak-s.dFast)*0.24;s.dSlow+=(peak-s.dSlow)*0.018;const quiet=s.dFast<=s.dSlow*1.15,nr=quiet?0.02:0.004;s.dNoise+=(s.dFast-s.dNoise)*nr;s.dNoise=Math.max(1e-7,s.dNoise);const snr=s.dFast/s.dNoise,openT=2.15,closeT=1.65;if(s.dOpen?snr<closeT:snr>openT)s.dOpen=!s.dOpen;const lo=Math.log10(closeT),hi=Math.log10(openT),x=Math.log10(Math.max(snr,1e-6));let p=clamp((x-lo)/(hi-lo),0,1);p=p*p*(3-2*p);if(!s.dOpen)p*=0.35;const red=18*amount*(1-p),target=Math.pow(10,-red/20);s.dGain+=(target-s.dGain)*(target<s.dGain?0.28:0.065);s.dGain=clamp(s.dGain,Math.pow(10,-18*amount/20),1);dg=s.dGain}let tg=1;if(Math.abs(punch)>0.0001||Math.abs(sustain)>0.0001){const smp=peak*dg;s.tFast+=(smp-s.tFast)*0.28;s.tSlow+=(smp-s.tSlow)*0.018;const tr=clamp((s.tFast-s.tSlow)/Math.max(s.tFast,1e-5),0,1),sr=clamp(s.tSlow/Math.max(s.tFast,1e-5),0,1);tg=clamp((1+punch*0.85*tr)*(1+sustain*0.45*sr),0.05,2.25)}for(let c=0;c<ch;c++)out.getChannelData(c)[i]=inp.getChannelData(c)[i]*dg*tg;for(let c=ch;c<out.numberOfChannels;c++)out.getChannelData(c)[i]=0}};return{band,eq,dry,neg,change,normal,deltaGate,proc,state}}
  function buildGraph(){const c=ensureCtx(),master=c.createGain(),analyser=c.createAnalyser();analyser.fftSize=2048;analyser.smoothingTimeConstant=.05;master.connect(analyser);analyser.connect(c.destination);const dryBus=c.createGain(),normalBus=c.createGain(),deltaBus=c.createGain(),dryMaster=c.createGain(),normalMaster=c.createGain(),deltaMaster=c.createGain();dryBus.connect(dryMaster);dryMaster.connect(master);normalBus.connect(normalMaster);normalMaster.connect(master);deltaBus.connect(deltaMaster);deltaMaster.connect(master);const stages=[];for(let i=0;i<N;i++){const s=makeStage();s.band.connect(s.dry);s.dry.connect(s.neg);s.neg.connect(s.change);s.band.connect(s.eq);s.eq.connect(s.proc);s.proc.connect(s.change);s.change.connect(s.normal);s.normal.connect(normalBus);s.change.connect(s.deltaGate);s.deltaGate.connect(deltaBus);stages.push(s)}graph={master,analyser,dryBus,normalBus,deltaBus,dryMaster,normalMaster,deltaMaster,stages};graphMode='ScriptProcessor';sync();return graph}
  function ensureGraph(){if(!graph)buildGraph();return Promise.resolve(graph)}
  function sync(){if(!graph||!ctx)return;const now=ctx.currentTime,a=data(),anySolo=a.some(b=>b.solo);graph.stages.forEach((s,i)=>{const b=a[i];s.state.settings=b;s.band.frequency.setTargetAtTime(b.freq,now,.003);s.band.Q.setTargetAtTime(clamp(b.q,.25,18),now,.003);s.eq.frequency.setTargetAtTime(b.freq,now,.003);s.eq.Q.setTargetAtTime(clamp(b.q,.25,18),now,.003);s.eq.gain.setTargetAtTime(b.gain,now,.003);const active=!allBypass&&!b.bypass&&(!anySolo||b.solo);s.normal.gain.setTargetAtTime(active&&!delta?1:0,now,.003);s.deltaGate.gain.setTargetAtTime(active&&delta===i+1?1:0,now,.003)});graph.dryMaster.gain.setTargetAtTime(allBypass||!delta?1:0,now,.003);graph.normalMaster.gain.setTargetAtTime(allBypass||delta?0:1,now,.003);graph.deltaMaster.gain.setTargetAtTime(allBypass?0:(delta?1:0),now,.003)}
  function disconnectSource(){if(!source)return;try{source.stop()}catch(_){ }try{source.disconnect()}catch(_){ }source=null}
  function loopBounds(){return buffer&&loopEnd>loopStart?[loopStart,loopEnd]:[0,buffer?buffer.duration:0]}
  function connectSource(){disconnectSource();source=ctx.createBufferSource();source.buffer=buffer;source.loop=loop;const[a,b]=loopBounds();if(b>a){source.loopStart=a;source.loopEnd=b}source.connect(graph.dryBus);graph.stages.forEach(s=>source.connect(s.band));sync()}
  async function start(){if(!buffer)return status('請先載入音檔。');try{const c=ensureCtx();await c.resume();await ensureGraph();connectSource();const[a,b]=loopBounds();offset=loop?clamp(offset,a,Math.max(a,b-.001)):clamp(offset,0,Math.max(0,buffer.duration-.001));startedAt=c.currentTime;source.start(0,offset);playing=true;$('play').textContent='❚❚ 停止';status(delta?`DELTA SECTION ${delta}：只聽 Wet−Dry`:(loop?'LOOP 播放中':'播放中'));tick()}catch(e){playing=false;disconnectSource();status('播放失敗：'+(e?.message||e));console.error(e)}}
  function stop(){if(playing&&ctx&&buffer){const el=Math.max(0,ctx.currentTime-startedAt),[a,b]=loopBounds();offset=loop&&b>a?a+((offset+el-a)%(b-a)+(b-a))%(b-a):clamp(offset+el,0,buffer.duration)}playing=false;disconnectSource();cancelAnimationFrame(raf);raf=0;$('play').textContent='▶ 播放';cursor(offset/(buffer?.duration||1));status('已停止')}
  function togglePlay(){playing?stop():start()}
  function tick(){if(!playing||!buffer||!ctx)return;const el=Math.max(0,ctx.currentTime-startedAt),[a,b]=loopBounds(),pos=loop&&b>a?a+((offset+el-a)%(b-a)+(b-a))%(b-a):offset+el;if(!loop&&pos>=buffer.duration)return stop();cursor(pos/buffer.duration);raf=requestAnimationFrame(tick)}
  function cursor(p){p=clamp(p,0,1);if($('cursorIn'))$('cursorIn').style.left=p*100+'%';if($('cursorOut'))$('cursorOut').style.left=p*100+'%';$('time').textContent=buffer?`${(p*buffer.duration).toFixed(2)} / ${buffer.duration.toFixed(2)} s`:'0.00 / 0.00 s'}
  function fft(re,im){for(let i=1,j=0;i<re.length;i++){let bit=re.length>>1;for(;j&bit;bit>>=1)j^=bit;j^=bit;if(i<j){[re[i],re[j]]=[re[j],re[i]];[im[i],im[j]]=[im[j],im[i]]}}for(let len=2;len<=re.length;len<<=1){const ang=-2*Math.PI/len,wr=Math.cos(ang),wi=Math.sin(ang);for(let i=0;i<re.length;i+=len){let ur=1,ui=0;for(let j=0;j<len/2;j++){const p=i+j,q=p+len/2,tr=re[q]*ur-im[q]*ui,ti=re[q]*ui+im[q]*ur;re[q]=re[p]-tr;im[q]=im[p]-ti;re[p]+=tr;im[p]+=ti;const nr=ur*wr-ui*wi;ui=ur*wi+ui*wr;ur=nr}}}}
  function drawSpectrogram(canvas,audioBuffer,processed=false){if(!canvas||!audioBuffer)return;const w=Math.max(1,Math.floor(canvas.clientWidth||1200)),h=Math.max(1,Math.floor(canvas.clientHeight||220)),dpr=Math.min(2,window.devicePixelRatio||1);canvas.width=Math.floor(w*dpr);canvas.height=Math.floor(h*dpr);const g=canvas.getContext('2d');g.setTransform(dpr,0,0,dpr,0,0);g.fillStyle='#02070a';g.fillRect(0,0,w,h);const ch0=audioBuffer.getChannelData(0),bins=256,fftN=512,cols=Math.min(w,900),hop=Math.max(1,Math.floor((ch0.length-fftN)/Math.max(1,cols-1)));for(let x=0;x<cols;x++){const start=Math.min(ch0.length-fftN,x*hop),re=new Float64Array(fftN),im=new Float64Array(fftN);for(let i=0;i<fftN;i++)re[i]=ch0[start+i]*(.5-.5*Math.cos(2*Math.PI*i/(fftN-1)));fft(re,im);for(let y=0;y<bins;y++){const k=Math.min(fftN/2-1,Math.floor(y*(fftN/2)/bins)),mag=Math.hypot(re[k],im[k])/fftN,db=20*Math.log10(Math.max(mag,1e-6));let norm=clamp((db+85)/75,0,1);if(processed){const hz=k*audioBuffer.sampleRate/fftN,bs=data(),affected=bs.some((b,idx)=>{const range=freqLimit(idx+1),inRange=hz>=range[0]*.45&&hz<=range[1]*1.8,dist=Math.abs(Math.log2(Math.max(hz,1)/Math.max(b.freq,1))),change=Math.abs(b.gain)/12+b.denoise/100+Math.max(Math.abs(b.punch),Math.abs(b.sustain))/100;return inRange&&dist<1.2&&change>.05&&!b.bypass&&(!bs.some(x=>x.solo)||b.solo)});if(!affected)norm=0}if(norm>.001){const hue=190+norm*130;g.fillStyle=`hsl(${hue} 85% ${18+norm*42}%)`;g.fillRect(x*w/cols,h-1-y*h/bins,Math.ceil(w/cols)+1,Math.ceil(h/bins)+1)}}}}
  function renderProcessed(){if(buffer)drawSpectrogram($('specOut'),buffer,true)}
  function renderProcessedSoon(){clearTimeout(renderTimer);renderTimer=setTimeout(renderProcessed,80)}
  async function loadFile(file){if(!file)return;try{stop();status('載入音檔中……');const c=ensureCtx(),bytes=await file.arrayBuffer(),decoded=await c.decodeAudioData(bytes.slice(0));buffer=decoded;offset=0;loopStart=0;loopEnd=0;loop=false;$('loop').textContent='LOOP OFF';$('loop').classList.remove('active');$('dropUi').style.display='none';$('fileInfo').textContent=`${file.name} · ${decoded.duration.toFixed(2)} s · ${decoded.sampleRate} Hz`;drawSpectrogram($('specIn'),buffer,false);renderProcessed();cursor(0);status('音檔已載入。')}catch(e){status('音檔載入失敗：'+(e?.message||e));console.error(e)}}
  function updateRange(rangeEl,start,end){if(!rangeEl||!(end>start)||!buffer){rangeEl?.classList.remove('show');return}rangeEl.style.left=start/buffer.duration*100+'%';rangeEl.style.width=(end-start)/buffer.duration*100+'%';rangeEl.classList.add('show')}
  function bindRange(id,rangeId){const frame=$(id),rangeEl=$(rangeId);if(!frame)return;frame.addEventListener('pointerdown',e=>{if(!buffer)return;const r=frame.getBoundingClientRect(),p=clamp((e.clientX-r.left)/r.width,0,1);drag={frame,start:p};frame.setPointerCapture?.(e.pointerId)});frame.addEventListener('pointermove',e=>{if(!drag||drag.frame!==frame||!buffer)return;const r=frame.getBoundingClientRect(),p=clamp((e.clientX-r.left)/r.width,0,1),a=Math.min(drag.start,p)*buffer.duration,b=Math.max(drag.start,p)*buffer.duration;updateRange(rangeEl,a,b)});frame.addEventListener('pointerup',e=>{if(!drag||drag.frame!==frame||!buffer)return;const r=frame.getBoundingClientRect(),p=clamp((e.clientX-r.left)/r.width,0,1),a=Math.min(drag.start,p)*buffer.duration,b=Math.max(drag.start,p)*buffer.duration;drag=null;if(b-a>=.02){loopStart=a;loopEnd=b;loop=true;$('loop').textContent='LOOP ON';$('loop').classList.add('active');updateRange($('rangeIn'),loopStart,loopEnd);updateRange($('rangeOut'),loopStart,loopEnd);status(`LOOP ${a.toFixed(2)}–${b.toFixed(2)} s`)}frame.releasePointerCapture?.(e.pointerId)});frame.addEventListener('dblclick',()=>{loopStart=0;loopEnd=0;loop=false;$('loop').textContent='LOOP OFF';$('loop').classList.remove('active');$('rangeIn').classList.remove('show');$('rangeOut').classList.remove('show');status('LOOP 已清除')})}
  function toggleLoop(){loop=!loop;$('loop').textContent=loop?'LOOP ON':'LOOP OFF';$('loop').classList.toggle('active',loop);if(loop&&buffer&&!(loopEnd>loopStart)){loopStart=0;loopEnd=buffer.duration;updateRange($('rangeIn'),loopStart,loopEnd);updateRange($('rangeOut'),loopStart,loopEnd)}status(loop?'LOOP 開啟':'LOOP 關閉')}
  function toggleBypassAll(){allBypass=!allBypass;$('bypassAll').classList.toggle('active',allBypass);$('bypassAll').textContent=allBypass?'BYPASS ON':'BYPASS OFF';sync();renderProcessedSoon();status(allBypass?'全部 Section BYPASS':'全部 Section ON')}
  function updateDelta(){document.querySelectorAll('[data-action="delta"]').forEach((b,i)=>b.classList.toggle('active',delta===i+1))}
  function setDelta(i){delta=delta===i?0:i;updateDelta();sync();renderProcessedSoon();status(delta?`DELTA SECTION ${delta}：只聽 Wet−Dry`:'DELTA 已關閉')}
  function toggleAB(){saveSlot();ab=ab==='A'?'B':'A';apply(clone(ab==='A'?slotA:slotB),false);$('ab').textContent='A/B · '+ab;status('切換到 '+ab)}
  function setupKnobs(){document.querySelectorAll('.knob-input').forEach(input=>{drawKnob(input,false);input.addEventListener('input',()=>{drawKnob(input,true);saveSlot();sync();renderProcessedSoon()});input.addEventListener('change',()=>drawKnob(input,false))});document.querySelectorAll('.knob').forEach(knob=>{const input=$(knob.dataset.target);if(!input)return;let startY=0,startValue=0,active=false;knob.addEventListener('pointerdown',e=>{active=true;startY=e.clientY;startValue=+input.value;knob.classList.add('active');knob.setPointerCapture?.(e.pointerId);drawKnob(input,true)});knob.addEventListener('pointermove',e=>{if(!active)return;const key=input.id.replace(/\d+$/,''),i=+(input.id.match(/\d+$/)?.[0]||1),[min,max]=limitFor(key,i);setKnob(input,startValue+(startY-e.clientY)*(max-min)/240,true)});const end=()=>{active=false;knob.classList.remove('active');drawKnob(input,false)};knob.addEventListener('pointerup',end);knob.addEventListener('pointercancel',end);knob.addEventListener('wheel',e=>{e.preventDefault();const key=input.id.replace(/\d+$/,''),i=+(input.id.match(/\d+$/)?.[0]||1),[min,max]=limitFor(key,i);setKnob(input,+input.value-e.deltaY*((max-min)/240)*.18,true)},{passive:false});knob.addEventListener('keydown',e=>{const key=input.id.replace(/\d+$/,''),i=+(input.id.match(/\d+$/)?.[0]||1),[,,step]=limitFor(key,i);if(e.key==='ArrowUp'||e.key==='ArrowRight'){e.preventDefault();setKnob(input,+input.value+step,true)}if(e.key==='ArrowDown'||e.key==='ArrowLeft'){e.preventDefault();setKnob(input,+input.value-step,true)}})})}
  function setupUI(){setupKnobs();$('play').addEventListener('click',togglePlay);$('stop').addEventListener('click',stop);$('loop').addEventListener('click',toggleLoop);$('bypassAll').addEventListener('click',toggleBypassAll);$('ab').addEventListener('click',toggleAB);$('resetAll').addEventListener('click',resetAll);$('resetBands').addEventListener('click',resetBands);$('sortBtn').addEventListener('click',sortBands);document.querySelectorAll('[data-action="bypass"]').forEach((b,i)=>b.addEventListener('click',()=>setBypass(i+1,!b.classList.contains('on'))));document.querySelectorAll('[data-action="delta"]').forEach((b,i)=>b.addEventListener('click',()=>setDelta(i+1)));document.querySelectorAll('[data-action="reset"]').forEach((b,i)=>b.addEventListener('click',()=>resetBand(i+1)));document.querySelectorAll('[data-action="solo"]').forEach((b,i)=>b.addEventListener('click',()=>setSolo(i+1,!b.classList.contains('active'))));$('file').addEventListener('change',e=>loadFile(e.target.files?.[0]));const inputFrame=$('inputFrame'),dropUi=$('dropUi');[inputFrame,dropUi].forEach(el=>{el.addEventListener('dragover',e=>e.preventDefault());el.addEventListener('drop',e=>{e.preventDefault();loadFile(e.dataTransfer?.files?.[0])})});document.addEventListener('keydown',e=>{if(e.code!=='Space'||e.repeat)return;const t=e.target;if(t&&(t.tagName==='INPUT'||t.tagName==='TEXTAREA'||t.isContentEditable))return;e.preventDefault();togglePlay()});bindRange('inputFrame','rangeIn');bindRange('outputFrame','rangeOut');window.addEventListener('resize',()=>{if(buffer){drawSpectrogram($('specIn'),buffer,false);renderProcessed()}})}
  function debugState(){const bands=data(),anySolo=bands.some(b=>b.solo),graphFreqs=graph?graph.stages.map(s=>s.band.frequency.value):[],normalGates=graph?graph.stages.map(s=>s.normal.gain.value):[],deltaGates=graph?graph.stages.map(s=>s.deltaGate.gain.value):[];return{loaded:!!buffer,playing,loop,loopStart,loopEnd,delta,allBypass,graphReady:!!graph,graphMode,audioState:ctx?.state||'none',sampleRate:ctx?.sampleRate||0,anySolo,soloBands:bands.map((b,i)=>b.solo?i+1:0).filter(Boolean),bands,freqRanges:FREQ_RANGES.map(x=>[...x]),graphFreqs,normalGates,deltaGates,activeBands:bands.map((b,i)=>(!allBypass&&!b.bypass&&(!anySolo||b.solo))?i+1:0).filter(Boolean)}}
  function meterRms(){if(!graph?.analyser)return 0;const arr=new Uint8Array(graph.analyser.fftSize);graph.analyser.getByteTimeDomainData(arr);let sum=0;for(let i=0;i<arr.length;i++){const x=(arr[i]-128)/128;sum+=x*x}return Math.sqrt(sum/arr.length)}
  window.myEFX={loadFile,togglePlay,stopPlayback:stop,currentData:data,debugState,meterRms,freqRanges:FREQ_RANGES};resetAll();if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',setupUI,{once:true});else setupUI();
})();
