/* myEFX 8-band Web Tester
   8 compact sections inspired by the workflow of MAAT thEQorange.
   File input, playback, per-band bypass, Delta and spectral rendering are kept independent.
*/
let ctx=null,buffer=null,source=null,outputGain=null,analyser=null;
let stages=[],playing=false,loopEnabled=false,bypassAll=false,playStartTime=0,playOffset=0,rafId=0,loopCycle=-1;
let deltaBand=0,currentSlot='A',renderTimer=0,renderToken=0;
const BAND_COUNT=8;
const defaults=[31.5,63,125,250,500,1000,2500,8000].map(freq=>({freq,gain:0,q:1,denoise:0,punch:0,sustain:0,bypass:false}));
let slotA=cloneDefaults(),slotB=cloneDefaults();
const $=id=>document.getElementById(id);
const pKeys=['freq','gain','q','denoise','punch','sustain'];
function cloneDefaults(){return defaults.map(x=>({...x}));}
function uiValue(i,k){return Number($(k+i).value);}
function setStatus(t){const el=$('status');if(el)el.textContent=t;}
function fmtHz(v){return v>=1000?`${(v/1000).toFixed(v>=10000?1:2)} kHz`:`${Number(v).toFixed(v%1?1:0)} Hz`;}
function clamp(v,a,b){return Math.max(a,Math.min(b,v));}
function updateBandState(i){const active=$('byp'+i)?.classList.contains('on');if($('state'+i))$('state'+i).textContent=active?'ON':'BYP';}
function readBands(){return Array.from({length:BAND_COUNT},(_,n)=>{const i=n+1;return{freq:uiValue(i,'freq'),gain:uiValue(i,'gain'),q:uiValue(i,'q'),denoise:uiValue(i,'denoise'),punch:uiValue(i,'punch'),sustain:uiValue(i,'sustain'),bypass:!$('byp'+i)?.classList.contains('on')}})}
function applyBands(data){for(let i=1;i<=BAND_COUNT;i++){const b=data[i-1]||defaults[i-1];$('freq'+i).value=clamp(+b.freq||defaults[i-1].freq,20,20000);$('gain'+i).value=clamp(+b.gain||0,-24,24);$('q'+i).value=clamp(+b.q||1,.1,20);$('denoise'+i).value=clamp(+b.denoise||0,0,100);$('punch'+i).value=clamp(+b.punch||0,-100,100);$('sustain'+i).value=clamp(+b.sustain||0,-100,100);const on=!b.bypass;$('byp'+i).classList.toggle('on',on);$('byp'+i).classList.toggle('off',!on);updateBandState(i);}syncAll();}
function saveCurrent(){const d=readBands();if(currentSlot==='A')slotA=d;else slotB=d;}
function resetAll(){applyBands(cloneDefaults());saveCurrent();setStatus('所有 Sections 已重設。');}
function resetBand(i){const b=defaults[i-1];$('freq'+i).value=b.freq;$('gain'+i).value=0;$('q'+i).value=1;$('denoise'+i).value=0;$('punch'+i).value=0;$('sustain'+i).value=0;$('byp'+i).classList.add('on');$('byp'+i).classList.remove('off');updateBandState(i);syncAll();saveCurrent();}
function sortBands(){const d=readBands().sort((a,b)=>a.freq-b.freq);applyBands(d);saveCurrent();setStatus('Sections 已由低頻到高頻排序。');}
function createStage(){
 const eq=ctx.createBiquadFilter();eq.type='peaking';
 const pass=ctx.createBiquadFilter();pass.type='bandpass';
 const rawMinus=ctx.createGain();rawMinus.gain.value=-1;
 const processedMinus=ctx.createGain();processedMinus.gain.value=-1;
 const out=ctx.createGain();
 const dDry=ctx.createGain(),dWet=ctx.createGain(),dSum=ctx.createGain();
 const fallbackComp=ctx.createDynamicsCompressor();fallbackComp.attack.value=.003;fallbackComp.release.value=.08;fallbackComp.knee.value=12;fallbackComp.ratio.value=20;
 const tDry=ctx.createGain(),tWet=ctx.createGain(),tSum=ctx.createGain();
 const deltaEq=ctx.createBiquadFilter();deltaEq.type='peaking';
 const deltaRawMinus=ctx.createGain();deltaRawMinus.gain.value=-1;
 const deltaMix=ctx.createGain();deltaMix.gain.value=1;
 const deltaSum=ctx.createGain();
 eq.connect(out);
 pass.connect(rawMinus);rawMinus.connect(out);
 pass.connect(dDry);pass.connect(dWet);dDry.connect(dSum);dWet.connect(fallbackComp);fallbackComp.connect(dSum);
 dSum.connect(tDry);dSum.connect(tWet);tDry.connect(tSum);
 dSum.connect(processedMinus);processedMinus.connect(out);
 tWet.connect(tSum);tSum.connect(out);
 pass.connect(deltaEq);deltaEq.connect(deltaRawMinus);deltaRawMinus.connect(deltaSum);
 tSum.connect(deltaMix);deltaMix.connect(deltaSum);
 return{eq,pass,rawMinus,out,dDry,dWet,dSum,fallbackComp,tDry,tWet,tSum,processedMinus,deltaEq,deltaRawMinus,deltaMix,deltaSum,transient:null,denoise:null,enabled:true};
}
async function createDenoise(s){if(!ctx?.audioWorklet||s.denoise)return;try{await ctx.audioWorklet.addModule('denoise-processor.js?v=2');s.denoise=new AudioWorkletNode(ctx,'myefx-denoise',{parameterData:{amount:0,threshold:1.5,reduction:30,adaptation:1,smoothing:38,transientProtect:72,tonalProtect:12,learn:0}});s.dWet.disconnect();s.dWet.connect(s.denoise);s.denoise.connect(s.dSum);}catch(e){s.denoise=null;console.warn('denoise worklet',e)}}
async function createTransient(s){if(!ctx?.audioWorklet||s.transient)return;try{await ctx.audioWorklet.addModule('transient-processor.js?v=15');s.transient=new AudioWorkletNode(ctx,'myefx-transient',{parameterData:{punch:0,sustain:0}});s.tWet.disconnect();s.tWet.connect(s.transient);s.transient.connect(s.tSum);}catch(e){s.transient=null;console.warn('transient worklet',e)}}
async function ensureGraph(){
 if(!ctx)ctx=new AudioContext();
 if(!stages.length)for(let i=0;i<BAND_COUNT;i++)stages.push(createStage());
 if(!outputGain)outputGain=ctx.createGain();
 if(!analyser){analyser=ctx.createAnalyser();analyser.fftSize=2048;analyser.smoothingTimeConstant=.02;}
 for(const s of stages){await createDenoise(s);await createTransient(s);}
 syncAll(false);
}
function syncAll(schedule=true){if(!ctx||!stages.length)return;syncParams();if(schedule)scheduleProcessedRender();}
function syncParams(){
 for(let i=1;i<=BAND_COUNT;i++){
  const s=stages[i-1],f=uiValue(i,'freq'),q=uiValue(i,'q'),g=uiValue(i,'gain'),dn=uiValue(i,'denoise'),pu=uiValue(i,'punch'),su=uiValue(i,'sustain'),enabled=$('byp'+i)?.classList.contains('on');
  s.enabled=enabled;s.eq.frequency.value=f;s.eq.Q.value=q;s.eq.gain.value=enabled?g:0;s.pass.frequency.value=f;s.pass.Q.value=q;s.deltaEq.frequency.value=f;s.deltaEq.Q.value=q;s.deltaEq.gain.value=enabled?g:0;
  if(s.denoise){const p=s.denoise.parameters;p.get('amount')?.setValueAtTime(enabled?dn:0,ctx.currentTime);p.get('threshold')?.setValueAtTime(1.5,ctx.currentTime);p.get('reduction')?.setValueAtTime(30,ctx.currentTime);p.get('adaptation')?.setValueAtTime(1,ctx.currentTime);p.get('smoothing')?.setValueAtTime(38,ctx.currentTime);p.get('transientProtect')?.setValueAtTime(72,ctx.currentTime);p.get('tonalProtect')?.setValueAtTime(12,ctx.currentTime);}else{s.dDry.gain.value=enabled&&dn>0?0:1;s.dWet.gain.value=enabled&&dn>0?1:0;s.fallbackComp.threshold.value=-60+(dn/100)*35;s.fallbackComp.ratio.value=1+(dn/100)*39;}
  const mix=Math.min(1,(Math.abs(pu)+Math.abs(su))/200);s.tDry.gain.value=enabled?(1-mix):1;s.tWet.gain.value=enabled?mix:0;if(s.transient){s.transient.parameters.get('punch')?.setValueAtTime(enabled?pu:0,ctx.currentTime);s.transient.parameters.get('sustain')?.setValueAtTime(enabled?su:0,ctx.currentTime);}s.deltaMix.gain.value=enabled?1:0;updateBandState(i);
 }
}
function disconnectPlayback(){try{source?.stop()}catch{}try{source?.disconnect()}catch{}try{outputGain?.disconnect()}catch{}try{analyser?.disconnect()}catch{}for(const s of stages)try{s.deltaSum.disconnect()}catch{}source=null;}
function connectCommonOutput(){outputGain.connect(analyser);analyser.connect(ctx.destination);}
function buildPlayback(){
 disconnectPlayback();source=ctx.createBufferSource();source.buffer=buffer;source.loop=loopEnabled;source.loopStart=0;source.loopEnd=buffer.duration;
 if(bypassAll){source.connect(ctx.destination);return;}
 if(deltaBand>0){const s=stages[deltaBand-1];source.connect(s.pass);s.deltaSum.connect(outputGain);connectCommonOutput();return;}
 let node=source;for(const s of stages){node.connect(s.eq);node.connect(s.pass);node=s.out;}node.connect(outputGain);connectCommonOutput();
}
async function start(){
 if(!buffer){setStatus('請先載入音檔。');return;}
 try{if(!ctx)ctx=new AudioContext();await ctx.resume();await ensureGraph();syncParams();buildPlayback();playStartTime=ctx.currentTime;loopCycle=-1;source.start(0,clamp(playOffset,0,Math.max(0,buffer.duration-.001)));playing=true;$('play').textContent='❚❚ 播放中';setStatus(deltaBand?`DELTA B${deltaBand} 播放中`:(bypassAll?'BYPASS 播放中':'播放中'));updateCursor();}
 catch(e){playing=false;setStatus('播放失敗：'+(e?.message||e));console.error(e);}
}
function stop(){if(playing&&ctx&&buffer){const elapsed=Math.max(0,ctx.currentTime-playStartTime);playOffset=loopEnabled?(playOffset+elapsed)%buffer.duration:Math.min(buffer.duration,playOffset+elapsed);}playing=false;disconnectPlayback();cancelAnimationFrame(rafId);rafId=0;$('play').textContent='▶ 播放';setCursor(buffer?playOffset/buffer.duration:0);setStatus('已停止');}
function toggleLoop(){loopEnabled=!loopEnabled;$('loop').textContent=`LOOP ${loopEnabled?'ON':'OFF'}`;$('loop').classList.toggle('active',loopEnabled);if(source){source.loop=loopEnabled;source.loopEnd=buffer.duration;}}
function toggleBypassAll(){bypassAll=!bypassAll;$('bypassAll').textContent=`BYPASS ${bypassAll?'ON':'OFF'}`;$('bypassAll').classList.toggle('active',bypassAll);if(playing){const p=playOffset;stop();playOffset=p;start();}}
function setCursor(r){const x=`${clamp(r,0,1)*100}%`;if($('cursorIn'))$('cursorIn').style.left=x;if($('cursorOut'))$('cursorOut').style.left=x;if($('time'))$('time').textContent=buffer?`${(clamp(r,0,1)*buffer.duration).toFixed(2)} / ${buffer.duration.toFixed(2)} s`:'0.00 / 0.00 s';}
function updateCursor(){if(!playing||!ctx||!buffer)return;const elapsed=ctx.currentTime-playStartTime,total=playOffset+elapsed;let pos=total/buffer.duration;if(loopEnabled)pos=(total%buffer.duration)/buffer.duration;if(!loopEnabled&&pos>=1){pos=1;playing=false;disconnectPlayback();$('play').textContent='▶ 播放';setStatus('播放結束');}setCursor(pos);if(playing)rafId=requestAnimationFrame(updateCursor);}
function fft(re,im){const n=re.length;for(let i=1,j=0;i<n;i++){let bit=n>>1;for(;j&bit;bit>>=1)j^=bit;j^=bit;if(i<j){let t=re[i];re[i]=re[j];re[j]=t;t=im[i];im[i]=im[j];im[j]=t;}}for(let len=2;len<=n;len<<=1){const a=-2*Math.PI/len,wr0=Math.cos(a),wi0=Math.sin(a);for(let i=0;i<n;i+=len){let wr=1,wi=0,h=len>>1;for(let j=0;j<h;j++){const uR=re[i+j],uI=im[i+j],vR=re[i+j+h]*wr-im[i+j+h]*wi,vI=re[i+j+h]*wi+im[i+j+h]*wr;re[i+j]=uR+vR;im[i+j]=uI+vI;re[i+j+h]=uR-vR;im[i+j+h]=uI-vI;const tr=wr*wr0-wi*wi0;wi=wr*wi0+wi*wr0;wr=tr;}}}}
function color(v){const x=clamp(v,0,1);const r=Math.floor(255*Math.min(1,Math.max(0,(x-.64)*3.1))),g=Math.floor(255*Math.min(1,Math.max(0,(x-.30)*2.2))),b=Math.floor(255*Math.min(1,Math.max(0,(x-.05)*2.8)));return`rgb(${r|0},${g|0},${b|0})`;}
function responseDbAt(freq){let total=0;for(let i=1;i<=BAND_COUNT;i++){if(!$('byp'+i).classList.contains('on'))continue;const fc=uiValue(i,'freq'),gain=uiValue(i,'gain'),q=Math.max(.1,uiValue(i,'q')),x=Math.log2(Math.max(20,freq)/fc),shape=Math.exp(-.5*Math.pow(x*q*2,2));total+=gain*shape;}return total;}
const bandColors=['#ff5a4f','#ff8f3d','#f4c63d','#b9dc43','#72d45c','#38d7b8','#35bfe7','#8a8ff7'];
function drawResponseOverlay(g,w,h){const top=Math.min(84,Math.max(65,Math.round(h*.20))),y0=top*.67,scale=Math.max(7,Math.min(15,top*.18));g.save();g.fillStyle='rgba(2,7,10,.82)';g.fillRect(0,0,w,top);g.strokeStyle='rgba(130,165,173,.24)';g.lineWidth=1;for(const f of [20,50,100,200,500,1000,2000,5000,10000,20000]){const x=Math.log10(f/20)/3*w;g.beginPath();g.moveTo(x,0);g.lineTo(x,top);g.stroke();g.fillStyle='#6f858d';g.font='8px sans-serif';g.fillText(f>=1000?f/1000+'k':f,x+2,top-4);}g.strokeStyle='rgba(225,245,247,.4)';g.beginPath();g.moveTo(0,y0);g.lineTo(w,y0);g.stroke();g.beginPath();for(let x=0;x<w;x++){const f=20*Math.pow(1000,x/Math.max(1,w-1)*3),db=clamp(responseDbAt(f),-18,18),y=y0-db*scale/12;x?g.lineTo(x,y):g.moveTo(x,y);}g.strokeStyle='#f5ffff';g.lineWidth=2;g.stroke();for(let i=1;i<=BAND_COUNT;i++){const fc=uiValue(i,'freq'),x=Math.log10(fc/20)/3*w,db=clamp(responseDbAt(fc),-18,18),y=y0-db*scale/12;g.fillStyle=bandColors[i-1];g.beginPath();g.arc(x,y,3.5,0,Math.PI*2);g.fill();g.font='bold 7px sans-serif';g.fillText('B'+i,x+4,y-5);}g.restore();}
function drawSpectrogram(audio,canvas){if(!audio||!canvas)return;const token=++renderToken,frame=512,w=Math.max(640,Math.min(1000,Math.floor(canvas.clientWidth))),h=Math.max(180,Math.min(360,Math.floor(canvas.clientHeight))),g=canvas.getContext('2d',{alpha:false});canvas.width=w;canvas.height=h;g.fillStyle='#02070a';g.fillRect(0,0,w,h);const top=canvas=== $('specIn')?Math.min(82,Math.max(62,Math.round(h*.20))):0,specH=h-top,L=audio.getChannelData(0),R=audio.numberOfChannels>1?audio.getChannelData(1):L,re=new Float32Array(frame),im=new Float32Array(frame),win=new Float32Array(frame);for(let i=0;i<frame;i++)win[i]=.5-.5*Math.cos(2*Math.PI*i/(frame-1));let x=0;function paint(){if(token!==renderToken)return;const end=Math.min(w,x+20);for(;x<end;x++){const center=Math.floor(x/Math.max(1,w-1)*(audio.length-1)),start=center-(frame>>1);for(let n=0;n<frame;n++){const idx=clamp(start+n,0,audio.length-1);re[n]=((L[idx]+R[idx])*.5)*win[n];im[n]=0;}fft(re,im);for(let y=top;y<h;y++){const f=20*Math.pow(1000,1-(y-top)/Math.max(1,specH-1)),bin=clamp(Math.round(f*frame/audio.sampleRate),1,frame>>1),db=20*Math.log10(Math.hypot(re[bin],im[bin])/frame+1e-8);g.fillStyle=color((db+105)/81);g.fillRect(x,y,1,1);}}if(x<w)requestAnimationFrame(paint);else if(canvas===$('specIn'))drawResponseOverlay(g,w,h);}paint();}
function drawChangeSpectrogram(input,output,canvas){if(!input||!output||!canvas)return;const token=++renderToken,frame=512,w=Math.max(640,Math.min(1000,Math.floor(canvas.clientWidth))),h=Math.max(180,Math.min(360,Math.floor(canvas.clientHeight))),g=canvas.getContext('2d',{alpha:false});canvas.width=w;canvas.height=h;g.fillStyle='#02070a';g.fillRect(0,0,w,h);const L=input.getChannelData(0),R=input.numberOfChannels>1?input.getChannelData(1):L,OL=output.getChannelData(0),OR=output.numberOfChannels>1?output.getChannelData(1):OL,inRe=new Float32Array(frame),inIm=new Float32Array(frame),outRe=new Float32Array(frame),outIm=new Float32Array(frame),win=new Float32Array(frame);for(let i=0;i<frame;i++)win[i]=.5-.5*Math.cos(2*Math.PI*i/(frame-1));let x=0;function paint(){if(token!==renderToken)return;const end=Math.min(w,x+16);for(;x<end;x++){const center=Math.floor(x/Math.max(1,w-1)*(input.length-1)),start=center-(frame>>1);for(let n=0;n<frame;n++){const a=clamp(start+n,0,input.length-1),b=clamp(start+n,0,output.length-1);inRe[n]=((L[a]+R[a])*.5)*win[n];outRe[n]=((OL[b]+OR[b])*.5)*win[n];inIm[n]=outIm[n]=0;}fft(inRe,inIm);fft(outRe,outIm);for(let y=0;y<h;y++){const f=20*Math.pow(1000,1-y/Math.max(1,h-1)),bin=clamp(Math.round(f*frame/input.sampleRate),1,frame>>1),idb=20*Math.log10(Math.hypot(inRe[bin],inIm[bin])/frame+1e-8),odb=20*Math.log10(Math.hypot(outRe[bin],outIm[bin])/frame+1e-8),d=odb-idb,a=Math.abs(d);if(a<.5)continue;const cut=d<0,st=clamp((a-.5)/7,0,1),alpha=.30+.70*st;g.fillStyle=cut?`rgba(45,174,230,${alpha})`:`rgba(255,150,54,${alpha})`;g.fillRect(x,y,1,1);}}if(x<w)requestAnimationFrame(paint);}paint();}
async function renderOffline(){if(!buffer||!ctx)return null;const token=++renderToken,off=new OfflineAudioContext(2,buffer.length,buffer.sampleRate);await off.audioWorklet.addModule('denoise-processor.js?v=2');await off.audioWorklet.addModule('transient-processor.js?v=15');const nodes=[];for(let i=1;i<=BAND_COUNT;i++){const b={freq:uiValue(i,'freq'),gain:uiValue(i,'gain'),q:uiValue(i,'q'),denoise:uiValue(i,'denoise'),punch:uiValue(i,'punch'),sustain:uiValue(i,'sustain'),bypass:!$('byp'+i).classList.contains('on')};const eq=off.createBiquadFilter();eq.type='peaking';eq.frequency.value=b.freq;eq.Q.value=b.q;eq.gain.value=b.bypass?0:b.gain;const pass=off.createBiquadFilter();pass.type='bandpass';pass.frequency.value=b.freq;pass.Q.value=b.q;const rawMinus=off.createGain();rawMinus.gain.value=-1;const out=off.createGain();eq.connect(out);pass.connect(rawMinus);rawMinus.connect(out);const dry=off.createGain(),wet=off.createGain(),sum=off.createGain();const dn=new AudioWorkletNode(off,'myefx-denoise',{parameterData:{amount:b.bypass?0:b.denoise,threshold:1.5,reduction:30,adaptation:1,smoothing:38,transientProtect:72,tonalProtect:12,learn:0}});dry.gain.value=b.bypass||b.denoise===0?1:0;wet.gain.value=b.bypass||b.denoise===0?0:1;pass.connect(dry);pass.connect(wet);dry.connect(sum);wet.connect(dn);dn.connect(sum);const td=off.createGain(),tw=off.createGain(),ts=off.createGain();const tr=new AudioWorkletNode(off,'myefx-transient',{parameterData:{punch:b.bypass?0:b.punch,sustain:b.bypass?0:b.sustain}});const mix=b.bypass?0:Math.min(1,(Math.abs(b.punch)+Math.abs(b.sustain))/200);td.gain.value=1-mix;tw.gain.value=mix;sum.connect(td);sum.connect(tw);td.connect(ts);tw.connect(tr);tr.connect(ts);ts.connect(out);nodes.push(out);}const src=off.createBufferSource();src.buffer=buffer;let node=src;for(const n of nodes){node.connect(n);node=n;}node.connect(off.destination);src.start();const out=await off.startRendering();return token===renderToken?out:null;}
function scheduleProcessedRender(){if(!buffer)return;clearTimeout(renderTimer);renderTimer=setTimeout(async()=>{if(playing)return;try{setStatus('分析實際變化中的頻率…');const out=await renderOffline();if(out&&!playing)drawChangeSpectrogram(buffer,out,$('specOut'));if(!playing)setStatus('Processed Spectrogram：只顯示實際改動');}catch(e){console.warn(e);setStatus('Processed Spectrogram 更新失敗：'+(e?.message||e));}},850);}
async function loadFile(file){if(!file)return;if(!/\.(wav|wave|aif|aiff|flac|mp3|m4a|ogg)$/i.test(file.name)&&!file.type.startsWith('audio/')){setStatus('請選擇音訊檔。');return;}stop();try{if(!ctx)ctx=new AudioContext();const bytes=await file.arrayBuffer();const decoded=await ctx.decodeAudioData(bytes.slice(0));buffer=decoded;playOffset=0;$('dropUi').style.display='none';$('fileInfo').textContent=`${file.name} · ${buffer.numberOfChannels}ch · ${buffer.sampleRate}Hz · ${buffer.duration.toFixed(2)}s`;setCursor(0);drawSpectrogram(buffer,$('specIn'));$('specOut').getContext('2d').clearRect(0,0,$('specOut').width,$('specOut').height);setStatus('音檔已載入。');await ensureGraph();scheduleProcessedRender();}catch(e){buffer=null;$('dropUi').style.display='flex';$('fileInfo').textContent='未載入';setStatus('音檔載入失敗：'+(e?.message||e));console.error('loadFile',e);}}
function setupFileInput(){const box=$('inputFrame'),file=$('file');box.addEventListener('click',e=>{if(e.target===file)return;if(e.target.closest('.cursor'))return;if(buffer){const r=(e.clientX-box.getBoundingClientRect().left)/box.clientWidth;stop();playOffset=clamp(r,0,1)*buffer.duration;setCursor(r);}else file.click();});file.addEventListener('change',e=>{const f=e.target.files&&e.target.files[0];if(f)loadFile(f);e.target.value='';});let dragDepth=0;box.addEventListener('dragenter',e=>{e.preventDefault();dragDepth++;box.style.borderColor='#72ddd8';});box.addEventListener('dragover',e=>{e.preventDefault();e.dataTransfer.dropEffect='copy';});box.addEventListener('dragleave',e=>{e.preventDefault();dragDepth=Math.max(0,dragDepth-1);if(!dragDepth)box.style.borderColor='';});box.addEventListener('drop',e=>{e.preventDefault();dragDepth=0;box.style.borderColor='';const f=e.dataTransfer?.files?.[0];if(f)loadFile(f);});window.addEventListener('keydown',e=>{if(e.key==='Escape')file.value='';});}
function setDelta(i){deltaBand=deltaBand===i?0:i;document.querySelectorAll('[data-action="delta"]').forEach(b=>b.classList.toggle('active',+b.dataset.band===deltaBand));if(playing){const p=playOffset;stop();playOffset=p;start();}setStatus(deltaBand?`DELTA B${deltaBand}：只聽該頻段 DELTA`:'DELTA OFF');}
function toggleBandBypass(i){const b=$('byp'+i);const on=!b.classList.contains('on');b.classList.toggle('on',on);b.classList.toggle('off',!on);updateBandState(i);syncParams();saveCurrent();if(playing){const p=playOffset;stop();playOffset=p;start();}else scheduleProcessedRender();}
function toggleAB(){saveCurrent();currentSlot=currentSlot==='A'?'B':'A';$('ab').textContent=`A/B · ${currentSlot}`;applyBands(currentSlot==='A'?slotA:slotB);}
function bindControls(){for(let i=1;i<=BAND_COUNT;i++)for(const k of pKeys)$(k+i).addEventListener('input',()=>{syncParams();saveCurrent();scheduleProcessedRender();});document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const i=+b.dataset.band;if(b.dataset.action==='delta')setDelta(i);else if(b.dataset.action==='bypass')toggleBandBypass(i);else if(b.dataset.action==='reset')resetBand(i);});$('play').onclick=()=>playing?stop():start();$('stop').onclick=stop;$('loop').onclick=toggleLoop;$('bypassAll').onclick=toggleBypassAll;$('ab').onclick=toggleAB;$('resetAll').onclick=resetAll;$('resetBands').onclick=resetAll;$('sortBtn').onclick=sortBands;}
function init(){try{bindControls();setupFileInput();for(let i=1;i<=BAND_COUNT;i++)updateBandState(i);const ci=$('specIn'),co=$('specOut');ci.width=900;ci.height=240;co.width=900;co.height=205;setStatus('尚未載入音檔。');}catch(e){console.error('myEFX init',e);setStatus('初始化失敗：'+(e?.message||e));}}
init();
