/* myEFX Web Tester — clean native 4-band rebuild */
(()=>{
'use strict';
const BAND_COUNT=4;
const DEFAULTS=[{freq:31.5,gain:0,q:1,denoise:0,punch:0,sustain:0,bypass:false},{freq:125,gain:0,q:1,denoise:0,punch:0,sustain:0,bypass:false},{freq:1000,gain:0,q:1,denoise:0,punch:0,sustain:0,bypass:false},{freq:8000,gain:0,q:1,denoise:0,punch:0,sustain:0,bypass:false}];
const INFO={freq:{min:20,max:20000,step:1},gain:{min:-24,max:24,step:.1},q:{min:.1,max:20,step:.01},denoise:{min:0,max:100,step:1},punch:{min:-100,max:100,step:1},sustain:{min:-100,max:100,step:1}};
let ctx=null,buffer=null,source=null,graph=null,playing=false,loop=false,bypassAll=false,offset=0,startAt=0,raf=0,delta=0,token=0,renderToken=0,renderTimer=0,slot='A',slotA=clone(),slotB=clone(),workletsReady=false;
const $=id=>document.getElementById(id),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function clone(){return DEFAULTS.map(x=>({...x}));}
function status(t){$('status').textContent=t;}
function data(){return Array.from({length:BAND_COUNT},(_,n)=>{let i=n+1;return{freq:+$('freq'+i).value,gain:+$('gain'+i).value,q:+$('q'+i).value,denoise:+$('denoise'+i).value,punch:+$('punch'+i).value,sustain:+$('sustain'+i).value,bypass:!$('byp'+i).classList.contains('on')}});}
function save(){if(slot==='A')slotA=data();else slotB=data();}
function fmt(k,v){if(k==='freq')return v>=1000?(v/1000).toFixed(v>=10000?1:2)+' kHz':(v%1?v.toFixed(1):Math.round(v))+' Hz';if(k==='gain')return v.toFixed(1)+' dB';if(k==='q')return v.toFixed(2);return Math.round(v)+'%';}
function renderKnob(input){let k=input.id.replace(/[0-9]+$/,'');let d=INFO[k],v=+input.value,n=-135+270*(v-d.min)/(d.max-d.min),knob=document.querySelector('.knob[data-target="'+input.id+'"]');if(!knob)return;knob.querySelector('.knob-pointer').style.transform='translateX(-50%) rotate('+n+'deg)';$(input.id+'Out').textContent=fmt(k,v);}
function setInput(input,v){let k=input.id.replace(/[0-9]+$/,'');let d=INFO[k];v=clamp(Math.round(v/d.step)*d.step,d.min,d.max);let dec=(String(d.step).split('.')[1]||'').length;input.value=Number(v.toFixed(dec));input.dispatchEvent(new Event('input',{bubbles:true}));}
function setBypass(i,on,update=true){let b=$('byp'+i);b.classList.toggle('on',on);b.classList.toggle('off',!on);$('state'+i).textContent=on?'ON':'BYP';if(update){syncGraph();scheduleRender();}}
function apply(d){for(let i=1;i<=BAND_COUNT;i++){let b=d[i-1]||DEFAULTS[i-1];for(let k of Object.keys(INFO))$(''+k+i).value=clamp(+b[k],INFO[k].min,INFO[k].max);setBypass(i,!!b.bypass,false);renderKnob($('freq'+i));renderKnob($('gain'+i));renderKnob($('q'+i));renderKnob($('denoise'+i));renderKnob($('punch'+i));renderKnob($('sustain'+i));}syncGraph();}
function resetAll(){apply(clone());save();drawResponse();scheduleRender();status('所有 Sections 已重設。');}
function resetBand(i){let d=data();d[i-1]={...DEFAULTS[i-1]};apply(d);save();drawResponse();scheduleRender();status('SECTION '+i+' 已重設。');}
function ensureCtx(){if(!ctx||ctx.state==='closed')ctx=new AudioContext();return ctx;}
async function ensureWorklets(){if(workletsReady)return;let c=ensureCtx();await c.audioWorklet.addModule('denoise-processor.js?v=clean1');await c.audioWorklet.addModule('transient-processor.js?v=clean1');workletsReady=true;}
function stage(c){let eq=c.createBiquadFilter();eq.type='peaking';let split=c.createBiquadFilter();split.type='bandpass';let inv=c.createGain();inv.gain.value=-1;let out=c.createGain();let dry=c.createGain(),wet=c.createGain(),dSum=c.createGain(),tDry=c.createGain(),tWet=c.createGain(),tSum=c.createGain();eq.connect(out);split.connect(inv);inv.connect(out);split.connect(dry);split.connect(wet);dry.connect(dSum);wet.connect(dSum);dSum.connect(tDry);dSum.connect(tWet);tDry.connect(tSum);tWet.connect(tSum);tSum.connect(out);return{eq,split,inv,out,dry,wet,dSum,tDry,tWet,tSum,denoise:null,transient:null};}
async function ensureGraph(){let c=ensureCtx();if(!graph){let stages=Array.from({length:BAND_COUNT},()=>stage(c)),master=c.createGain(),analyser=c.createAnalyser();analyser.fftSize=2048;master.connect(analyser);analyser.connect(c.destination);graph={stages,master,analyser};}await ensureWorklets();for(let s of graph.stages){if(!s.denoise){s.denoise=new AudioWorkletNode(c,'myefx-denoise',{parameterData:{amount:0,threshold:1.5,reduction:30,adaptation:1,smoothing:38,transientProtect:72,tonalProtect:12,learn:0}});s.wet.disconnect();s.wet.connect(s.denoise);s.denoise.connect(s.dSum);}if(!s.transient){s.transient=new AudioWorkletNode(c,'myefx-transient',{parameterData:{punch:0,sustain:0}});s.tWet.disconnect();s.tWet.connect(s.transient);s.transient.connect(s.tSum);}}syncGraph();}
function syncGraph(){if(!graph||!ctx)return;let now=ctx.currentTime;data().forEach((b,i)=>{let s=graph.stages[i];s.eq.frequency.setTargetAtTime(b.freq,now,.004);s.eq.Q.setTargetAtTime(b.q,now,.004);s.eq.gain.setTargetAtTime(b.bypass?0:b.gain,now,.004);s.split.frequency.setTargetAtTime(b.freq,now,.004);s.split.Q.setTargetAtTime(b.q,now,.004);let dn=b.bypass?0:b.denoise;s.dry.gain.setTargetAtTime(b.bypass||b.denoise===0?1:0,now,.004);s.wet.gain.setTargetAtTime(b.bypass||b.denoise===0?0:1,now,.004);s.denoise?.parameters.get('amount')?.setTargetAtTime(dn,now,.004);let mix=b.bypass?0:Math.min(1,(Math.abs(b.punch)+Math.abs(b.sustain))/200);s.tDry.gain.setTargetAtTime(1-mix,now,.004);s.tWet.gain.setTargetAtTime(mix,now,.004);s.transient?.parameters.get('punch')?.setTargetAtTime(b.bypass?0:b.punch,now,.004);s.transient?.parameters.get('sustain')?.setTargetAtTime(b.bypass?0:b.sustain,now,.004);});}
function disconnect(){if(source){try{source.stop()}catch{}try{source.disconnect()}catch{}source=null;}}
function connectPlayback(){disconnect();source=ctx.createBufferSource();source.buffer=buffer;source.loop=loop;if(bypassAll){source.connect(ctx.destination);return;}if(delta){source.connect(graph.stages[delta-1].split);graph.stages[delta-1].tSum.connect(graph.master);return;}let n=source;for(let s of graph.stages){n.connect(s.eq);n.connect(s.split);n=s.out;}n.connect(graph.master);}
async function play(){if(!buffer){status('請先載入音檔。');return;}try{let c=ensureCtx();await c.resume();await ensureGraph();syncGraph();connectPlayback();startAt=c.currentTime;source.start(0,clamp(offset,0,Math.max(0,buffer.duration-.001)));playing=true;$('play').textContent='❚❚ 播放中';status(delta?'DELTA B'+delta+' 播放中':bypassAll?'BYPASS 播放中':'播放中');cursor();}catch(e){playing=false;status('播放失敗：'+(e.message||e));console.error(e);}}
function stop(){if(playing&&ctx&&buffer){let t=Math.max(0,ctx.currentTime-startAt);offset=loop?(offset+t)%buffer.duration:Math.min(buffer.duration,offset+t);}playing=false;disconnect();cancelAnimationFrame(raf);$('play').textContent='▶ 播放';setCursor(buffer?offset/buffer.duration:0);status('已停止');}
function cursor(){if(!playing||!buffer||!ctx)return;let p=(offset+(ctx.currentTime-startAt))/buffer.duration;if(loop)p=((offset+(ctx.currentTime-startAt))%buffer.duration)/buffer.duration;if(!loop&&p>=1){p=1;playing=false;disconnect();$('play').textContent='▶ 播放';status('播放結束');}setCursor(p);if(playing)raf=requestAnimationFrame(cursor);}
function setCursor(p){p=clamp(p,0,1);$('cursorIn').style.left=p*100+'%';$('cursorOut').style.left=p*100+'%';$('time').textContent=buffer?((p*buffer.duration).toFixed(2)+' / '+buffer.duration.toFixed(2)+' s'):'0.00 / 0.00 s';}
function fft(r,im){let n=r.length;for(let i=1,j=0;i<n;i++){let b=n>>1;for(;j&b;b>>=1)j^=b;j^=b;if(i<j){let t=r[i];r[i]=r[j];r[j]=t;t=im[i];im[i]=im[j];im[j]=t;}}for(let l=2;l<=n;l<<=1){let a=-2*Math.PI/l,w0=Math.cos(a),wi0=Math.sin(a);for(let i=0;i<n;i+=l){let wr=1,wi=0,h=l>>1;for(let j=0;j<h;j++){let u=r[i+j],ui=im[i+j],v=r[i+j+h]*wr-im[i+j+h]*wi,vi=r[i+j+h]*wi+im[i+j+h]*wr;r[i+j]=u+v;im[i+j]=ui+vi;r[i+j+h]=u-v;im[i+j+h]=ui-vi;let tr=wr*w0-wi*wi0;wi=wr*wi0+wi*w0;wr=tr;}}}}
function color(db){let v=clamp((db+90)/90,0,1),r=Math.floor(255*clamp((v-.62)*3,0,1)),g=Math.floor(255*clamp((v-.28)*2,0,1)),b=Math.floor(255*clamp((v-.02)*2.7,0,1));return`rgb(${r},${g},${b})`;}
function drawSpectrogram(audio,canvas,processed){let id=++renderToken,w=canvas.clientWidth||900,h=canvas.clientHeight||220,n=512,half=256,L=audio.getChannelData(0),R=audio.numberOfChannels>1?audio.getChannelData(1):L,PL=processed&&processed.getChannelData(0),PR=processed&&processed.numberOfChannels>1?processed.getChannelData(1):PL,re=new Float32Array(n),im=new Float32Array(n),pr=processed?new Float32Array(n):null,pi=processed?new Float32Array(n):null,win=new Float32Array(n);canvas.width=w;canvas.height=h;let g=canvas.getContext('2d',{alpha:false});g.fillStyle='#02070a';g.fillRect(0,0,w,h);for(let i=0;i<n;i++)win[i]=.5-.5*Math.cos(2*Math.PI*i/(n-1));let x=0;function paint(){if(id!==renderToken)return;for(let z=0;z<14&&x<w;z++,x++){let center=Math.floor(x/Math.max(1,w-1)*(L.length-1)),start=center-half;for(let i=0;i<n;i++){let j=clamp(start+i,0,L.length-1);re[i]=((L[j]+R[j])*.5)*win[i];im[i]=0;if(processed){let k=clamp(start+i,0,PL.length-1);pr[i]=((PL[k]+PR[k])*.5)*win[i];pi[i]=0;}}fft(re,im);if(processed)fft(pr,pi);for(let y=0;y<h;y++){let f=20*Math.pow(1000,1-y/Math.max(1,h-1)),bin=clamp(Math.round(f*n/audio.sampleRate),1,half),a=20*Math.log10(Math.hypot(re[bin],im[bin])/n+1e-8);if(!processed)g.fillStyle=color(a);else{let b=20*Math.log10(Math.hypot(pr[bin],pi[bin])/n+1e-8),d=b-a,s=clamp(Math.abs(d)/6,0,1);if(s<.03)continue;g.fillStyle=d<0?`rgba(45,174,230,${.2+.8*s})`:`rgba(255,150,54,${.2+.8*s})`;}g.fillRect(x,y,1,1);}}}if(x<w)requestAnimationFrame(paint)}paint();}
function response(freq){let total=0;for(let b of data()){if(b.bypass)continue;let s=Math.exp(-.5*Math.pow(Math.log2(Math.max(20,freq)/b.freq)*b.q*2,2));total+=b.gain*s;}return total;}
function drawResponse(){if(!buffer)return;let c=$('specIn'),g=c.getContext('2d'),w=c.width,h=c.height,top=76,y0=top*.66;g.fillStyle='rgba(2,7,10,.84)';g.fillRect(0,0,w,top);g.strokeStyle='rgba(120,160,170,.24)';g.lineWidth=1;for(let f of [20,50,100,200,500,1000,2000,5000,10000,20000]){let x=Math.log10(f/20)/3*w;g.beginPath();g.moveTo(x,0);g.lineTo(x,top);g.stroke();g.fillStyle='#73888f';g.font='8px sans-serif';g.fillText(f>=1000?f/1000+'k':f,x+2,top-4);}g.strokeStyle='#f4ffff';g.lineWidth=2;g.beginPath();for(let x=0;x<w;x++){let f=20*Math.pow(1000,x/Math.max(1,w-1)*3),y=y0-clamp(response(f),-18,18)*1.1;x?g.lineTo(x,y):g.moveTo(x,y);}g.stroke();}
function clearOut(){let c=$('specOut'),g=c.getContext('2d');g.clearRect(0,0,c.width,c.height);}
async function offline(input,d){let o=new OfflineAudioContext(2,input.length,input.sampleRate);await o.audioWorklet.addModule('denoise-processor.js?v=clean1');await o.audioWorklet.addModule('transient-processor.js?v=clean1');let ends=d.map(b=>{let eq=o.createBiquadFilter();eq.type='peaking';eq.frequency.value=b.freq;eq.Q.value=b.q;eq.gain.value=b.bypass?0:b.gain;let split=o.createBiquadFilter();split.type='bandpass';split.frequency.value=b.freq;split.Q.value=b.q;let inv=o.createGain();inv.gain.value=-1;let out=o.createGain();eq.connect(out);split.connect(inv);inv.connect(out);let dry=o.createGain(),wet=o.createGain(),sum=o.createGain();let dn=new AudioWorkletNode(o,'myefx-denoise',{parameterData:{amount:b.bypass?0:b.denoise,threshold:1.5,reduction:30,adaptation:1,smoothing:38,transientProtect:72,tonalProtect:12,learn:0}});dry.gain.value=b.bypass||!b.denoise?1:0;wet.gain.value=b.bypass||!b.denoise?0:1;split.connect(dry);split.connect(wet);dry.connect(sum);wet.connect(dn);dn.connect(sum);let td=o.createGain(),tw=o.createGain(),ts=o.createGain(),tr=new AudioWorkletNode(o,'myefx-transient',{parameterData:{punch:b.bypass?0:b.punch,sustain:b.bypass?0:b.sustain}}),mix=b.bypass?0:Math.min(1,(Math.abs(b.punch)+Math.abs(b.sustain))/200);td.gain.value=1-mix;tw.gain.value=mix;sum.connect(td);sum.connect(tw);td.connect(ts);tw.connect(tr);tr.connect(ts);ts.connect(out);return out});let s=o.createBufferSource();s.buffer=input;let node=s;for(let e of ends){node.connect(e);node=e;}node.connect(o.destination);s.start();return o.startRendering();}
async function renderProcessed(){if(!buffer||playing)return;let id=++renderToken;status('分析 Processed Spectrogram…');try{let out=await offline(buffer,data());if(id!==renderToken||playing)return;drawSpectrogram(buffer,$('specOut'),out);status('Processed Spectrogram 已更新。');}catch(e){clearOut();status('Processed Spectrogram 分析失敗：'+(e.message||e));console.warn(e);}}
function scheduleRender(){clearTimeout(renderTimer);if(!buffer||playing)return;renderTimer=setTimeout(renderProcessed,700);}
async function loadFile(file){if(!file)return;if(!file.type.startsWith('audio/')&&!/\.(wav|wave|aif|aiff|flac|mp3|m4a|ogg)$/i.test(file.name)){status('請選擇音訊檔。');return;}let id=++token;stop();buffer=null;offset=0;clearOut();$('fileInfo').textContent='讀取中…';status('1/3 讀取音檔…');try{let c=ensureCtx(),bytes=await file.arrayBuffer();if(id!==token)return;status('2/3 解碼 WAV / AIFF / FLAC / MP3…');let decoded=await c.decodeAudioData(bytes);if(id!==token)return;if(!decoded||!decoded.length)throw new Error('AudioBuffer 為空');buffer=decoded;$('dropUi').style.display='none';$('fileInfo').textContent=`${file.name} · ${buffer.numberOfChannels}ch · ${buffer.sampleRate}Hz · ${buffer.duration.toFixed(2)}s`;setCursor(0);requestAnimationFrame(()=>{if(id!==token||!buffer)return;drawSpectrogram(buffer,$('specIn'));drawResponse();status('3/3 音檔已載入；播放時才啟用 DSP。');scheduleRender();});}catch(e){if(id!==token)return;buffer=null;$('dropUi').style.display='flex';$('fileInfo').textContent='未載入';status('音檔載入失敗：'+(e.name==='NotSupportedError'?'瀏覽器不支援此格式':e.message||e));console.error(e);}}
function bindFile(){let frame=$('inputFrame'),file=$('file');file.addEventListener('change',e=>{let f=e.target.files?.[0];e.target.value='';if(f)loadFile(f);});frame.addEventListener('click',e=>{if(e.target.closest('.drop-card'))return;if(!buffer)file.click();else{let r=(e.clientX-frame.getBoundingClientRect().left)/frame.clientWidth;stop();offset=clamp(r,0,1)*buffer.duration;setCursor(r);}});frame.addEventListener('dragover',e=>{e.preventDefault();e.dataTransfer.dropEffect='copy';});frame.addEventListener('drop',e=>{e.preventDefault();e.stopPropagation();let f=e.dataTransfer?.files?.[0];if(f)loadFile(f);});window.addEventListener('dragover',e=>{if(e.dataTransfer?.files?.length)e.preventDefault();});window.addEventListener('drop',e=>{if(e.dataTransfer?.files?.length)e.preventDefault();});}
function bindKnobs(){document.querySelectorAll('.knob[data-target]').forEach(knob=>{let input=$(knob.dataset.target),active=false,y0=0,v0=0;renderKnob(input);knob.addEventListener('pointerdown',e=>{active=true;y0=e.clientY;v0=+input.value;knob.setPointerCapture?.(e.pointerId);e.preventDefault()});knob.addEventListener('pointermove',e=>{if(!active)return;let k=input.id.replace(/[0-9]+$/,''),r=INFO[k].max-INFO[k].min;setInput(input,v0+(y0-e.clientY)*r/190)});let end=e=>{active=false;try{knob.releasePointerCapture?.(e.pointerId)}catch{}};knob.addEventListener('pointerup',end);knob.addEventListener('pointercancel',end);knob.addEventListener('wheel',e=>{e.preventDefault();let k=input.id.replace(/[0-9]+$/,'');setInput(input,+input.value+(e.deltaY<0?INFO[k].step:-INFO[k].step))},{passive:false});knob.addEventListener('dblclick',e=>{e.preventDefault();setInput(input,+input.defaultValue)});knob.addEventListener('keydown',e=>{let k=input.id.replace(/[0-9]+$/,''),v=+input.value;if(e.key==='ArrowUp'||e.key==='ArrowRight')v+=INFO[k].step;else if(e.key==='ArrowDown'||e.key==='ArrowLeft')v-=INFO[k].step;else if(e.key==='Home')v=INFO[k].min;else if(e.key==='End')v=INFO[k].max;else if(e.key==='Enter')v=+input.defaultValue;else return;e.preventDefault();setInput(input,v)});input.addEventListener('input',()=>{renderKnob(input);save();syncGraph();drawResponse();scheduleRender();});});}
function bindButtons(){document.addEventListener('click',e=>{let b=e.target.closest('[data-action]');if(!b)return;let i=+b.closest('.band').dataset.band;if(b.dataset.action==='bypass')setBypass(i,!b.classList.contains('on'));if(b.dataset.action==='delta'){delta=delta===i?0:i;document.querySelectorAll('[data-action="delta"]').forEach(x=>x.classList.toggle('active',+x.closest('.band').dataset.band===delta));if(playing){let p=offset;stop();offset=p;play();}status(delta?'DELTA B'+delta+'：只聽該頻段':'DELTA OFF');}if(b.dataset.action==='reset')resetBand(i)});$('play').onclick=()=>playing?stop():play();$('stop').onclick=stop;$('loop').onclick=()=>{loop=!loop;$('loop').textContent='LOOP '+(loop?'ON':'OFF');$('loop').classList.toggle('active',loop)};$('bypassAll').onclick=()=>{bypassAll=!bypassAll;$('bypassAll').textContent='BYPASS '+(bypassAll?'ON':'OFF');$('bypassAll').classList.toggle('active',bypassAll);if(playing){let p=offset;stop();offset=p;play()}};$('ab').onclick=()=>{save();slot=slot==='A'?'B':'A';$('ab').textContent='A/B · '+slot;apply(slot==='A'?slotA:slotB);status('已切換至 '+slot+'。')};$('resetAll').onclick=resetAll;$('resetBands').onclick=resetAll;$('sortBtn').onclick=()=>{let d=data().sort((a,b)=>a.freq-b.freq);apply(d);save();drawResponse();scheduleRender();status('Sections 已由低頻到高頻排序。')};}
function init(){bindFile();bindKnobs();bindButtons();$('specIn').width=900;$('specIn').height=260;$('specOut').width=900;$('specOut').height=205;apply(clone());status('尚未載入音檔。');}
window.myEFX={loadFile,play,stop,currentData:data};
init();
})();
