/* myEFX stability + Delta patch */
(function(){
 const $=id=>document.getElementById(id); let fastRenderTimer=0,fastRenderToken=0;
 function fastSpecColor(v){const x=Math.max(0,Math.min(1,v));let r=Math.floor(255*Math.min(1,Math.max(0,(x-.64)*3.1))),g=Math.floor(255*Math.min(1,Math.max(0,(x-.30)*2.2))),b=Math.floor(255*Math.min(1,Math.max(0,(x-.05)*2.8)));if(x<.16){r*=.22;g*=.28;b*=.42}return`rgb(${r|0},${g|0},${b|0})`}
 window.drawSpectrogram=function(audio,canvas){if(!audio||!canvas)return;const token=++fastRenderToken,frame=512,w=Math.max(640,Math.min(1000,Math.floor(canvas.clientWidth))),h=Math.max(180,Math.min(360,Math.floor(canvas.clientHeight)));canvas.width=w;canvas.height=h;const g=canvas.getContext('2d',{alpha:false}),top=Math.min(86,Math.max(64,Math.round(h*.22))),specH=h-top,dataL=audio.getChannelData(0),dataR=audio.numberOfChannels>1?audio.getChannelData(1):dataL,re=new Float32Array(frame),im=new Float32Array(frame),win=new Float32Array(frame);for(let i=0;i<frame;i++)win[i]=.5-.5*Math.cos(2*Math.PI*i/(frame-1));g.fillStyle='#02080c';g.fillRect(0,0,w,h);let x=0;function paint(){if(token!==fastRenderToken)return;const end=Math.min(w,x+24);for(;x<end;x++){const center=Math.floor((x/Math.max(1,w-1))*Math.max(0,audio.length-1)),start=center-(frame>>1);for(let n=0;n<frame;n++){const idx=Math.max(0,Math.min(audio.length-1,start+n));re[n]=((dataL[idx]+dataR[idx])*.5)*win[n];im[n]=0}fft(re,im);for(let y=top;y<h;y++){const f=20*Math.pow(1000,1-(y-top)/Math.max(1,specH-1)),bin=Math.max(1,Math.min(frame>>1,Math.round(f*frame/audio.sampleRate))),db=20*Math.log10(Math.hypot(re[bin],im[bin])/frame+1e-8);g.fillStyle=fastSpecColor((db+105)/81);g.fillRect(x,y,1,1)}}if(x<w){requestAnimationFrame(paint);return}if(typeof drawResponseOverlay==='function')drawResponseOverlay(g,w,h,top)}paint()};
 window.scheduleProcessedRender=function(){if(!buffer)return;clearTimeout(fastRenderTimer);fastRenderTimer=setTimeout(async()=>{if(playing)return;const token=++fastRenderToken;try{$('status').textContent='重新分析 processed spectrogram…';const out=await renderOffline();if(token!==fastRenderToken||playing)return;if(out)drawSpectrogram(out,$('specOut'));$('status').textContent='Processed spectrogram 已更新'}catch(e){console.warn(e);$('status').textContent='Processed spectrogram 更新失敗：'+(e?.message||e)}},650)};
 window.buildPlayback=function(){disconnectAudio();source=ctx.createBufferSource();source.buffer=buffer;source.loop=loopEnabled;source.loopStart=0;source.loopEnd=buffer.duration;if(bypass){source.connect(ctx.destination);return}if(deltaBand>0){const s=stages[deltaBand-1];source.connect(s.prePass);source.connect(s.eq);try{s.deltaSum.disconnect()}catch{}s.deltaSum.connect(outputGain);outputGain.connect(analyser);analyser.connect(ctx.destination);return}let node=source;for(const s of stages){node.connect(s.eq);node=s.out}node.connect(outputGain);outputGain.connect(analyser);analyser.connect(ctx.destination)};
 window.setDelta=function(i){deltaBand=(deltaBand===i?0:i);document.querySelectorAll('[data-action="delta"]').forEach(b=>b.classList.toggle('active',+b.dataset.band===deltaBand));if(playing){const p=playOffset;stop();playOffset=p;start()}$('status').textContent=deltaBand?`DELTA B${deltaBand}：只聽該頻段 DELTA`:'Delta OFF'};
})();
